import { AppState } from './types';
import {
  ShieldIcon,
  UsersIcon,
  UserIcon,
  CrosshairIcon,
  DroneIcon,
  FirstAidIcon,
  SteeringWheelIcon,
  RadioIcon,
  ToolboxIcon,
  StarIcon,
  BinocularsIcon,
  CompassIcon,
  TargetIcon,
  BombIcon,
  DesktopIcon,
  CrownIcon,
  MedalIcon,
  CarIcon,
  JeepIcon,
  SwordIcon,
  KnifeIcon,
  SkullIcon,
  FlagIcon,
  MapTrifoldIcon,
  ParachuteIcon as PhosphorParachuteIcon,
  AnchorIcon,
  AirplaneTiltIcon,
  SirenIcon,
  MegaphoneIcon,
  TentIcon,
  TreeEvergreenIcon,
  FireIcon,
  LightningIcon,
  BroadcastIcon,
  WrenchIcon,
  TruckIcon,
  GavelIcon,
  FingerprintIcon,
  LockKeyIcon,
  SneakerIcon,
  TrophyIcon,
  CpuIcon,
  BugIcon
} from '@phosphor-icons/react';

import { 
  GiTank, 
  GiMachineGunMagazine, 
  GiRifle, 
  GiPistolGun, 
  GiDynamite, 
  GiTankTread, 
  GiJetFighter, 
  GiJeep, 
  GiSpyglass, 
  GiCompass,
  GiPoliceOfficerHead,
  GiBullets,
  GiGrenade,
  GiTellerMine,
  GiMortar,
  GiCrosshair,
  GiSubmarine,
  GiMilitaryAmbulance,
  GiBrodieHelmet,
  GiGasMask,
  GiParachute,
  GiTrenchBodyArmor,
  GiBoots,
  GiBackpack,
  GiRadarDish,
  GiSatelliteCommunication,
  GiWatchtower,
  GiMedicalPack,
  GiHandcuffs,
  GiSentryGun,
  GiCaltrops,
  GiStealthBomber,
  GiArtilleryShell,
  GiBarracks,
  GiBarracksTent,
  GiBunker,
  GiBattleship,
  GiAirForce,
  GiAlliedStar,
  GiPoliceBadge,
  GiCorporal,
  GiMedal,
  GiMetalPlate
} from "react-icons/gi";
import { 
  FaGun, 
  FaWalkieTalkie, 
  FaPersonRifle, 
  FaUserShield, 
  FaSatelliteDish, 
  FaTowerObservation 
} from "react-icons/fa6";
import { 
  FaBomb, 
  FaHelicopter, 
  FaTruckMonster, 
  FaShip, 
  FaStarOfDavid, 
  FaTruck,
  FaMapMarkedAlt,
  FaMedkit
} from "react-icons/fa";
import { SiRocket } from "react-icons/si";
import { MdMedicalServices, MdExplore, MdSecurity, MdBluetoothSearching } from "react-icons/md";
import { BsShieldFillCheck, BsBuildingsFill } from "react-icons/bs";

export const ROLE_ICONS: Record<string, any> = {
  shield: ShieldIcon,
  users: UsersIcon,
  user: UserIcon,
  rifle: CrosshairIcon,
  drone: DroneIcon,
  medic: FirstAidIcon,
  driver: SteeringWheelIcon,
  car: CarIcon,
  jeep: JeepIcon,
  radio: RadioIcon,
  mechanic: ToolboxIcon,
  command: StarIcon,
  recon: BinocularsIcon,
  nav: CompassIcon,
  target: TargetIcon,
  grenade: BombIcon,
  computer: DesktopIcon,
  commander: CrownIcon,
  officer: MedalIcon,
  sword: SwordIcon,
  knife: KnifeIcon,
  skull: SkullIcon,
  flag: FlagIcon,
  map: MapTrifoldIcon,
  parachute: PhosphorParachuteIcon,
  anchor: AnchorIcon,
  plane: AirplaneTiltIcon,
  siren: SirenIcon,
  megaphone: MegaphoneIcon,
  tent: TentIcon,
  tree: TreeEvergreenIcon,
  fire: FireIcon,
  lightning: LightningIcon,
  broadcast: BroadcastIcon,
  wrench: WrenchIcon,
  truck: TruckIcon,
  gavel: GavelIcon,
  fingerprint: FingerprintIcon,
  lock: LockKeyIcon,
  sneaker: SneakerIcon,
  trophy: TrophyIcon,
  cpu: CpuIcon,
  bug: BugIcon,
  // Gi (Game Icons)
  giTank: GiTank,
  magazine: GiMachineGunMagazine,
  giRifle: GiRifle,
  pistol: GiPistolGun,
  dynamite: GiDynamite,
  tread: GiTankTread,
  jet: GiJetFighter,
  giJeep: GiJeep,
  bullets: GiBullets,
  giGrenade: GiGrenade,
  mine: GiTellerMine,
  mortar: GiMortar,
  scope: GiCrosshair,
  submarine: GiSubmarine,
  ambulance: GiMilitaryAmbulance,
  helmet: GiBrodieHelmet,
  gasmask: GiGasMask,
  parachute2: GiParachute,
  vest: GiTrenchBodyArmor,
  boots: GiBoots,
  backpack: GiBackpack,
  radar: GiRadarDish,
  satellite: GiSatelliteCommunication,
  tower: GiWatchtower,
  medpack: GiMedicalPack,
  handcuffs: GiHandcuffs,
  sentry: GiSentryGun,
  caltrops: GiCaltrops,
  stealth: GiStealthBomber,
  artillery: GiArtilleryShell,
  barracks: GiBarracks,
  tent2: GiBarracksTent,
  bunker: GiBunker,
  battleship: GiBattleship,
  airForce: GiAirForce,
  star2: GiAlliedStar,
  police: GiPoliceBadge,
  corporal: GiCorporal,
  giMedal: GiMedal,
  officer2: GiPoliceOfficerHead,
  spyglass: GiSpyglass,
  compass2: GiCompass,
  dogtags: GiMetalPlate,
  // Fa6 (Font Awesome 6)
  gun2: FaGun,
  walkie: FaWalkieTalkie,
  soldier: FaPersonRifle,
  security: FaUserShield,
  dish: FaSatelliteDish,
  observation: FaTowerObservation,
  // Fa (Font Awesome)
  bomb2: FaBomb,
  helicopter: FaHelicopter,
  monster: FaTruckMonster,
  ship: FaShip,
  magenDavid: FaStarOfDavid,
  truck2: FaTruck,
  map2: FaMapMarkedAlt,
  kit: FaMedkit,
  // Si / Md / Bs
  rocket: SiRocket,
  medical: MdMedicalServices,
  explore: MdExplore,
  security2: MdSecurity,
  bluetooth: MdBluetoothSearching,
  shieldCheck: BsShieldFillCheck,
  buildings: BsBuildingsFill,
};

export const MOCK_ROLES = [];
export const MOCK_TEAMS = [];
export const MOCK_PEOPLE = [];
export const MOCK_TASKS = [];

export const MOCK_INITIAL_STATE: AppState = {
  people: [],
  roles: [],
  teams: [],
  taskTemplates: [],
  shifts: [],
  constraints: [],
  teamRotations: [],
  settings: null,
  absences: [],
  equipment: [],
  equipmentDailyChecks: [],
  hourlyBlockages: []
};