import { AppState } from './types';
import { 
    Shield as ShieldIcon, 
    Users as UsersIcon, 
    User as UserIcon,
    Crosshair as CrosshairIcon,
    Drone as DroneIcon,
    FirstAid as FirstAidIcon,
    SteeringWheel as SteeringWheelIcon,
    Radio as RadioIcon,
    Toolbox as ToolboxIcon,
    Star as StarIcon,
    Binoculars as BinocularsIcon,
    Compass as CompassIcon,
    Target as TargetIcon,
    Bomb as BombIcon,
    Desktop as DesktopIcon,
    Crown as CrownIcon,
    Medal as MedalIcon,
    Car as CarIcon,
    Jeep as JeepIcon,
    Sword as SwordIcon,
    Knife as KnifeIcon,
    Skull as SkullIcon,
    Flag as FlagIcon,
    MapTrifold as MapTrifoldIcon,
    Parachute as ParachuteIcon,
    Anchor as AnchorIcon,
    AirplaneTilt as AirplaneTiltIcon,
    Siren as SirenIcon,
    Megaphone as MegaphoneIcon,
    Tent as TentIcon,
    TreeEvergreen as TreeEvergreenIcon,
    Fire as FireIcon,
    Lightning as LightningIcon,
    Broadcast as BroadcastIcon,
    Wrench as WrenchIcon,
    Truck as TruckIcon,
    Gavel as GavelIcon,
    Fingerprint as FingerprintIcon,
    LockKey as LockKeyIcon,
    Sneaker as SneakerIcon,
    Trophy as TrophyIcon,
    Cpu as CpuIcon,
    Bug as BugIcon
} from '@phosphor-icons/react';

export const ROLE_ICONS: Record<string, any> = {
    shield: ShieldIcon,
    users: UsersIcon,
    user: UserIcon,
    rifle: CrosshairIcon,
    drone: DroneIcon,
    medic: FirstAidIcon,
    driver: SteeringWheelIcon,
    car: CarIcon,
    jeep: JeepIcon,
    radio: RadioIcon,
    mechanic: ToolboxIcon,
    command: StarIcon,
    recon: BinocularsIcon,
    nav: CompassIcon,
    target: TargetIcon,
    grenade: BombIcon,
    computer: DesktopIcon,
    commander: CrownIcon,
    officer: MedalIcon,
    sword: SwordIcon,
    knife: KnifeIcon,
    skull: SkullIcon,
    flag: FlagIcon,
    map: MapTrifoldIcon,
    parachute: ParachuteIcon,
    anchor: AnchorIcon,
    plane: AirplaneTiltIcon,
    siren: SirenIcon,
    megaphone: MegaphoneIcon,
    tent: TentIcon,
    tree: TreeEvergreenIcon,
    fire: FireIcon,
    lightning: LightningIcon,
    broadcast: BroadcastIcon,
    wrench: WrenchIcon,
    truck: TruckIcon,
    gavel: GavelIcon,
    fingerprint: FingerprintIcon,
    lock: LockKeyIcon,
    sneaker: SneakerIcon,
    trophy: TrophyIcon,
    cpu: CpuIcon,
    bug: BugIcon,
};

export const MOCK_ROLES = [];
export const MOCK_TEAMS = [];
export const MOCK_PEOPLE = [];
export const MOCK_TASKS = [];

export const MOCK_INITIAL_STATE: AppState = {
  people: [],
  roles: [],
  teams: [],
  taskTemplates: [],
  shifts: [],
  constraints: [],
  teamRotations: [],
  settings: null,
  absences: [],
  equipment: [],
  hourlyBlockages: []
};