import { AppState } from './types';
import {
  ShieldIcon,
  UsersIcon,
  UserIcon,
  CrosshairIcon,
  DroneIcon,
  FirstAidIcon,
  SteeringWheelIcon,
  RadioIcon,
  ToolboxIcon,
  StarIcon,
  BinocularsIcon,
  CompassIcon,
  TargetIcon,
  BombIcon,
  DesktopIcon,
  CrownIcon,
  MedalIcon,
  CarIcon,
  JeepIcon,
  SwordIcon,
  KnifeIcon,
  SkullIcon,
  FlagIcon,
  MapTrifoldIcon,
  ParachuteIcon,
  AnchorIcon,
  AirplaneTiltIcon,
  SirenIcon,
  MegaphoneIcon,
  TentIcon,
  TreeEvergreenIcon,
  FireIcon,
  LightningIcon,
  BroadcastIcon,
  WrenchIcon,
  TruckIcon,
  GavelIcon,
  FingerprintIcon,
  LockKeyIcon,
  SneakerIcon,
  TrophyIcon,
  CpuIcon,
  BugIcon
} from '@phosphor-icons/react';

export const ROLE_ICONS: Record<string, any> = {
  shield: ShieldIcon,
  users: UsersIcon,
  user: UserIcon,
  rifle: CrosshairIcon,
  drone: DroneIcon,
  medic: FirstAidIcon,
  driver: SteeringWheelIcon,
  car: CarIcon,
  jeep: JeepIcon,
  radio: RadioIcon,
  mechanic: ToolboxIcon,
  command: StarIcon,
  recon: BinocularsIcon,
  nav: CompassIcon,
  target: TargetIcon,
  grenade: BombIcon,
  computer: DesktopIcon,
  commander: CrownIcon,
  officer: MedalIcon,
  sword: SwordIcon,
  knife: KnifeIcon,
  skull: SkullIcon,
  flag: FlagIcon,
  map: MapTrifoldIcon,
  parachute: ParachuteIcon,
  anchor: AnchorIcon,
  plane: AirplaneTiltIcon,
  siren: SirenIcon,
  megaphone: MegaphoneIcon,
  tent: TentIcon,
  tree: TreeEvergreenIcon,
  fire: FireIcon,
  lightning: LightningIcon,
  broadcast: BroadcastIcon,
  wrench: WrenchIcon,
  truck: TruckIcon,
  gavel: GavelIcon,
  fingerprint: FingerprintIcon,
  lock: LockKeyIcon,
  sneaker: SneakerIcon,
  trophy: TrophyIcon,
  cpu: CpuIcon,
  bug: BugIcon,
};

export const MOCK_ROLES = [];
export const MOCK_TEAMS = [];
export const MOCK_PEOPLE = [];
export const MOCK_TASKS = [];

export const MOCK_INITIAL_STATE: AppState = {
  people: [],
  roles: [],
  teams: [],
  taskTemplates: [],
  shifts: [],
  constraints: [],
  teamRotations: [],
  settings: null,
  absences: [],
  equipment: [],
  equipmentDailyChecks: [],
  hourlyBlockages: []
};